### ISSUE TITLE
error 'STAPSK'

### ISSUE THREAD

**Issue by Dancopy** [aamarioneta/vfd-max6921#1]
Greetings.
After a few years, I'm trying your code but it's showing the following: error: 'STAPSK' was not declared in this scope. I'm using ESP8266 version 2.4.1. Before, I was using the most recent version of ESP8266 but it was showing a Timezone library error. I couldn't find the TimeLib.h file; and in the Timezone folder, there is no TimeLib.h, so I found it quite confusing.
Could you please tell me which version of ESP8266 you used your code on? I'm almost giving up. Thank you very much.
P.S.: Another error: redefinition of 'const uint8_t D0'

**Comment by Dancopy** [comment]
> Greetings. After a few years, I'm trying your code but it's showing the following: error: 'STAPSK' was not declared in this scope. I'm using ESP8266 version 2.4.1. Before, I was using the most recent version of ESP8266 but it was showing a Timezone library error. I couldn't find the TimeLib.h file; and in the Timezone folder, there is no TimeLib.h, so I found it quite confusing. Could you please tell me which version of ESP8266 you used your code on? I'm almost giving up. Thank you very much. P.S.: Another error: redefinition of 'const uint8_t D0'

I think it will work.
1) Although my board is ESP8266 NodeMCU, in the Arduino IDE, I replaced the NodeMCU 1.0 board with Generic ESP8266 Module (ESP-12EModule).
2) I was calling credentials.h, so I created a new tab in the Arduino IDE with that same name and wrote:
#define STASSID "SSID"
#define STAPSK "PASSWORD".
Finally, Compilation finished.
I hope everything works out. Thanks

**Comment by aamarioneta** [comment]
yes, the credentials file is just an example, you have to copy it and fill it out.
i'm glad it worked out for you.
now i'm curious about your project - let my know what you are building?

**Comment by aamarioneta** [comment]
> I was using the most recent version of ESP8266 but it was showing a Timezone library error. I couldn't find the TimeLib.h file; and in the Timezone folder, there is no TimeLib.h, so I found it quite confusing.

I was using this lib at the time https://github.com/JChristensen/Timezone. You probably have to install it.

> P.S.: Another error: redefinition of 'const uint8_t D0'

The pins are probably defined for the board already.

**Comment by Dancopy** [comment]
Greetings @aamarioneta.
First of all, thank you for your answer. I don't know if you can continue to answer me here, but I have two more questions:
1) I would like to add the seconds count to my VFD, but I don't know how to do it in the code because there are 2 more digits.
2) I would also like to make 2 static elements of the VFD light up (permanently), which is the clock symbol and the word ON.
I will be sending you a photo of my VFD for you to check.
If you can answer me, I would be very grateful.
Daniel Fernandes
![VFD Futaba VLS02 B](https://github.com/user-attachments/assets/05918cc3-ea87-4ee0-a719-de11ecae8bcb)

**Comment by Dancopy** [comment]
I forgot to tell you that the 2 digits of the Seconds that I want to add, are the two digits that are at the bottom right of the VFD, which are in Grid 10 (Segments 14-20 and 20-28).

**Comment by aamarioneta** [comment]
> I would like to add the seconds count to my VFD, but I don't know how to do it in the code because there are 2 more digits.

It's been some time since i made this but as far as i can remember the max6921 can control 20 outputs. In my code i think i used all of them (or almost).

7 segments + 8 digits (hour, minute, day, month) + some for the day of the week (cant remember exactly how i did those) + 1 for the divider between hours and minutes.
But you can cascade multiple max6921's.

The other limitation is on how many digital outputs the esp32 has. I am not sure if i used all of them which can be used without messing with the pins reserved for flashing, booting and so on.  

For the "always on" symbols, you should just light them up on every cycle.

Hope this helps. Also, play with the DELAY constant, which is the number of microseconds between cycles.

**Comment by Dancopy** [comment]
Thanks, I'll try.

**Comment by Dancopy** [comment]
I didn't want to bother you but...
1) Where should I put the function to Write the Seconds Digits (Tens and Units)?
Would it be like this?

int hourTens[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
int hourOnes[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0}; int minuteTens[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0};
int minuteOnes[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0};
int secondTens[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, X, 0, 0, 0, 0, 0};
int secondOnes[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, X, 0, 0, 0, 0, 0, 0, 0, 0};
int dayTens[20] = { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
int dayOnes[20] = { 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
...
...

2) How should I make the word "ON" light up, which is on Grid 5 Pin 21?

3) And the pins for the days of the week, such as SU, Mo, Tu..., are they configured here?
int allOn[20] = {00, 00, 00, 00, 00, 00, 00, 01, 00, 01, 00, 00, 01, 01, 00, 01, 00, 01, 00, 01, 00, 01};

Sorry, I'm very interested in Arduino but I have a lot of difficulty understanding the code.

Thank you very much once again.

**Comment by aamarioneta** [comment]
first tip: use code formatting in the comments: use ` and ``` 

You must find out which pins of the VFD are the groups and which ones are the anodes of **your** VFD. They are different than my VFD. See this [video](https://www.youtube.com/watch?v=oxMdLEGoQgU). Then connect the VFD pins to the ESP32 pins and adjust the matrixes hourTens, hourOnes, ... accordingly.

1. you must use a free ESP32 pin. In my code for example, ESP32 pin 12 and pin 26 are not used. So it could look something link this
```
/* Pin No          26 25 24 23 22 21 20 19 18 17 12 11 10  9  8  7  6  5  4  3 */
int dayTens[20] = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
int dayOnes[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0};
```
2. same as for seconds, you need to connect the VFD pins for the group (i assume 5 in your case) and the segment (i assume 21 in your case) to a ESP32 pin. Then on every cycle in the function loop() you must turn these on with something like this
```
writeDigit(groupForTheWordON, 1, 1);
```
3. afaik in my vfd the days of the week are connected in a weird way - there are groups for sunday, monday, thursday, and the other days are on the minute ones and tens group. you must find out how the days are wired on **your** vfd and adjust the matrix's accordingly.

**Comment by Dancopy** [comment]
Thank you very much for your explanations.

**Comment by Dancopy** [comment]
Hello friend; I'm lost on something: the Segment pins are specified in "Pin Num > OUTx" but, what about the VFD Grids, where are they specified in the code? How do I know where to connect each VFD Grid to which Pin of the Max6921?
Because, in the ESP8266/ESP32 only these 3 wires are connected: int clk = D8; int load = D1; int din = D2;
Am I right?
Thanks again.

**Comment by aamarioneta** [comment]
Which MAX6921 pins are connected to the VFD for each group are defined in the variables `hourTens`, `hourOnes`, ...
e.g. for `hourOnes`: it's the pin #4 (the position where the 1 is in the array) - [here](https://github.com/aamarioneta/vfd-max6921/blob/master/max6921_clock/max6921_clock.ino#L55)

The segments of the digits are defined in [array](https://github.com/aamarioneta/vfd-max6921/blob/master/max6921_clock/max6921_clock.ino#L65) `d`:
```
/* Pin No / Segments
  10
17  09
  19
03  07
  11
*/
```
e.g. the bottom line of each digit (the bottom line of the character 8) is pin #11.

here are 2 more pics:
![vfd1](https://github.com/user-attachments/assets/82ed827b-8c0b-476a-b5b8-9d9be8e2f090)
![vfd2](https://github.com/user-attachments/assets/e043da21-65ed-4a7f-b2f1-ee9dc1140ff8)

**Comment by aamarioneta** [comment]
Now that i opened the box i see the confusion: in my [comment ](https://github.com/aamarioneta/vfd-max6921/issues/1#issuecomment-2395977790) i was talking about the ESP pins

> use a free ESP32 pin

which is of course **wrong** - i meant the MAX6921 pins. And it's not a ESP32 but ESP8266

Sorry about the confusion.

**Comment by Dancopy** [comment]
> Now that i opened the box i see the confusion: in my [comment ](https://github.com/aamarioneta/vfd-max6921/issues/1#issuecomment-2395977790) i was talking about the ESP pins
> 
> > use a free ESP32 pin
> 
> which is of course **wrong** - i meant the MAX6921 pins. And it's not a ESP32 but ESP8266
> 
> Sorry about the confusion.

**Comment by Dancopy** [comment]
Ah! Or are these the Grids?!
int hourTens[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
...........
...........
int minuteOnes[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0};

**Comment by Dancopy** [comment]
I will try and, if you have any questions, if you allow me, I will get back to you. Thanks.

**Comment by Dancopy** [comment]
Hello friend! One more question, please:
The pins:
"int hourTens[20]"
...
...
int groupTuesday[20]

can't they match (conflict) with these pins?

int d[10][20] = {
{ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1}, //0
{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0}, //1

In other words, the arrays above cannot be repeated in the array below?

Thank you

**Comment by aamarioneta** [comment]
From your question (the answer is 'no') i think that you need to understand better how a VFD works before you start looking at the code. play with your vfd, find out which pins are the grids and which ones are the segments.
![image](https://github.com/user-attachments/assets/a1830148-4340-4097-82a0-d3823a00c284)
See this image: the circled area on the right is a group. There is a group for every other digit - you can see the metal paths on the vfd board (the ones with the number 1, 2, 3, 4, CH in this - but these numbers don't mean anything).
The segments are the ones the arrows point at.
You must turn on a group and a segment at the same time so that something lights up. then you light up the next segment. you repeat this very fast and it looks like all are lit up at the same time.
In my code the variables hoursTens, hoursOnes, .. are the pins of the groups. the variable `d` contains the pins of the segments.
